import {z} from 'zod';
import {DEFAULT_CONFIG,type RunRecord} from '../../../packages/contracts';
import type {SimulationClient} from './simulation';
type AppApi={sim:SimulationClient;getState:()=>any;startFlight:(options?:any)=>Promise<void>;stop:()=>Promise<void>;train:()=>Promise<any>;runExperiment:()=>Promise<any>;evaluate:()=>Promise<any>;captureFrame:(expectedStep:number)=>Promise<{step:number;dataUrl:string}>};
declare global{interface Window{dronelab:AppApi;droneTools:{dispatch:typeof dispatch;list:()=>unknown};}}
const id=crypto.randomUUID();const jobs=new Map<string,{id:string;type:string;status:string;result?:unknown;error?:string}>();const artifacts=new Map<string,unknown>();
const api=()=>{if(!window.dronelab)throw new Error('Browser session is initializing');return window.dronelab;};
const empty=z.object({}).strict();
const schemas={list_scenarios:empty,get_capabilities:empty,create_session:empty,get_observation:empty,reset_session:z.object({scenario:z.enum(['hover','gates','landing','free']).optional(),seed:z.number().int().min(0).max(0xffffffff).optional()}).strict(),set_mission:z.object({scenario:z.enum(['hover','gates','landing','free']),seed:z.number().int().min(0).max(0xffffffff).optional()}).strict(),pause_session:empty,stop_session:empty,start_experiment:empty,get_run_status:z.object({jobId:z.string()}).strict(),cancel_run:z.object({jobId:z.string()}).strict(),summarize_run:z.object({runId:z.string()}).strict(),start_training:empty,get_training_status:z.object({jobId:z.string()}).strict(),list_policies:empty,capture_frame:z.object({expectedStep:z.number().int().nonnegative()}).strict(),export_dataset:z.object({runId:z.string()}).strict()};
type ToolName=keyof typeof schemas;
function startJob(type:string,fn:()=>Promise<unknown>){if([...jobs.values()].some(j=>j.status==='running'))throw new Error('A tool job is already running');if(jobs.size>=32)jobs.delete(jobs.keys().next().value!);const job={id:crypto.randomUUID(),type,status:'running'} as {id:string;type:string;status:string;result?:unknown;error?:string};jobs.set(job.id,job);void fn().then(result=>{if(job.status==='running'){job.status='completed';job.result=Array.isArray(result)?{runs:result.map((r:RunRecord)=>({id:r.id,metrics:r.metrics}))}:result&&typeof result==='object'&&'id'in result?{id:result.id}:result;}}).catch(error=>{if(job.status==='running'){job.status='failed';job.error=String(error);}});return {jobId:job.id,status:job.status};}
export async function dispatch(name:string,input:unknown={}){if(!(name in schemas))throw new Error('Unknown tool');const args=schemas[name as ToolName].parse(input) as any;const a=api();const s=a.getState();switch(name){case 'list_scenarios':return ['hover','gates','landing','free'];case 'get_capabilities':return {authority:'browser-worker',physics:'Rapier',stateObservations:true,rgb:!!a.captureFrame,training:'behavior cloning / CPU',remoteBackendRequired:false,clock:['realtime','lockstep'],maxEpisodes:32,maxSeconds:120};case 'create_session':return {sessionId:id,generation:a.sim.generation,authorityEpoch:a.sim.epoch};case 'get_observation':return a.sim.request('get');case 'reset_session':{const config={...DEFAULT_CONFIG,...s.currentConfig,...args};return a.sim.request('reset',{config,controller:s.controller??'manual'});}case 'set_mission':await a.startFlight({controller:'scripted',config:{...args}});return {accepted:true,scenario:args.scenario};case 'pause_session':return a.sim.request('mode',{mode:'paused'});case 'stop_session':await a.stop();return {stopped:true};case 'start_experiment':return startJob(name,()=>a.runExperiment());case 'start_training':return startJob(name,()=>a.train());case 'get_run_status':case 'get_training_status':{const job=jobs.get(args.jobId);if(!job)throw new Error('Unknown job');return {...job,progress:a.getState().training};}case 'cancel_run':{const job=jobs.get(args.jobId);if(!job)throw new Error('Unknown job');await a.stop();job.status='cancelled';return job;}case 'list_policies':return (s.policies??[]).map((p:any)=>({id:p.id,scenario:p.scenario,hash:p.hash,epochs:p.epochs}));case 'summarize_run':{const run=(s.runs as RunRecord[]).find(r=>r.id===args.runId);if(!run)throw new Error('Run not found');return {id:run.id,metrics:run.metrics,manifest:run.manifest};}case 'capture_frame':{const frame=await a.captureFrame(args.expectedStep);if(frame.dataUrl.length>8_000_000)throw new Error('Capture exceeds 8 MB limit');const artifactId=crypto.randomUUID();artifacts.set(artifactId,frame);if(artifacts.size>8)artifacts.delete(artifacts.keys().next().value!);return {artifactId,step:frame.step,format:'image/png',scope:'this browser tab'};}case 'export_dataset':{const run=(s.runs as RunRecord[]).find(r=>r.id===args.runId);if(!run)throw new Error('Run not found');const artifactId=crypto.randomUUID();artifacts.set(artifactId,run);if(artifacts.size>8)artifacts.delete(artifacts.keys().next().value!);return {artifactId,transitions:run.transitions.length,scope:'this browser tab',schema:'run-v1'};}default:throw new Error('Unsupported tool');}}
export function attachAgentTools(){window.droneTools={dispatch,list:()=>Object.keys(schemas)};const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();for(const [name,schema]of Object.entries(schemas)){void Promise.resolve(context.registerTool({name,description:`DroneLab ${name.replaceAll('_',' ')} in the active browser session.`,inputSchema:z.toJSONSchema(schema),annotations:{readOnlyHint:['list_scenarios','get_capabilities','get_observation','get_run_status','get_training_status','list_policies','summarize_run'].includes(name),untrustedContentHint:false},execute:(args:unknown)=>dispatch(name,args)},{signal:lifecycle.signal})).catch(()=>{/* Optional experimental browser API. */});}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
