import {openDB,type DBSchema} from 'idb';
import {zipSync,strToU8} from 'fflate';
import type {PolicyCheckpoint,RunRecord,Transition} from '../../../packages/contracts';
import {validateCheckpoint} from '../../../packages/learning';
interface LabDB extends DBSchema{runs:{key:string;value:RunRecord};chunks:{key:string;value:{id:string;runId:string;index:number;transitions:Transition[]};indexes:{runId:string}};policies:{key:string;value:PolicyCheckpoint};}
const db=()=>openDB<LabDB>('dronelab',1,{upgrade(db){db.createObjectStore('runs',{keyPath:'id'});const chunks=db.createObjectStore('chunks',{keyPath:'id'});chunks.createIndex('runId','runId');db.createObjectStore('policies',{keyPath:'id'});}});
const activeRuns=new Set<string>();
export async function saveRun(run:RunRecord){if(run.transitions.length>14400)throw new Error('Recording limit exceeded');const d=await db();const tx=d.transaction(['runs','chunks'],'readwrite');await tx.objectStore('runs').put(structuredClone(run));if(run.status==='recording')activeRuns.add(run.id);else{activeRuns.delete(run.id);for(const c of await tx.objectStore('chunks').index('runId').getAll(run.id))await tx.objectStore('chunks').delete(c.id);}const all=await tx.objectStore('runs').getAll();if(all.length>64){for(const old of all.sort((a,b)=>a.createdAt.localeCompare(b.createdAt)).slice(0,all.length-64)){await tx.objectStore('runs').delete(old.id);for(const c of await tx.objectStore('chunks').index('runId').getAll(old.id))await tx.objectStore('chunks').delete(c.id);}}await tx.done;}
export async function appendChunk(id:string,index:number,transitions:Transition[]){const d=await db();const tx=d.transaction(['chunks','runs'],'readwrite');await tx.objectStore('chunks').put({id:`${id}:${index}`,runId:id,index,transitions});await tx.done;}
export async function listRuns(){const d=await db();const runs=await d.getAll('runs');for(const run of runs){if(run.status==='recording'&&!activeRuns.has(run.id)){const chunks=(await d.getAllFromIndex('chunks','runId',run.id)).sort((a,b)=>a.index-b.index);run.transitions=chunks.flatMap(c=>c.transitions);run.status='interrupted';}}return runs.sort((a,b)=>b.createdAt.localeCompare(a.createdAt));}
export async function deleteRun(id:string){const d=await db();const tx=d.transaction(['runs','chunks'],'readwrite');await tx.objectStore('runs').delete(id);for(const c of await tx.objectStore('chunks').getAll())if(c.runId===id)await tx.objectStore('chunks').delete(c.id);await tx.done;}
export async function savePolicy(policy:PolicyCheckpoint){validateCheckpoint(policy);const d=await db();await d.put('policies',structuredClone(policy));}
export async function listPolicies(){const policies=await (await db()).getAll('policies');policies.forEach(validateCheckpoint);return policies.sort((a,b)=>b.createdAt.localeCompare(a.createdAt));}
export function download(name:string,data:BlobPart,type='application/json'){const blob=new Blob([data],{type});const href=URL.createObjectURL(blob);const a=document.createElement('a');a.href=href;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(href),1000);}
export function exportRun(run:RunRecord){validateRun(run);const header=['run_id','controller','seed','success','reason','seconds','collisions','tracking_error_m','energy_proxy','reward'];const m=run.metrics;const row=[run.id,run.controller,run.config.seed,m.success,m.reason,m.seconds,m.collisions,m.trackingError,m.energy,m.reward];const zip=zipSync({'manifest.json':strToU8(JSON.stringify({...run,transitions:undefined},null,2)),'transitions.jsonl':strToU8(run.transitions.map(t=>JSON.stringify(t)).join('\n')),'events.jsonl':strToU8(run.transitions.filter(t=>t.terminated||t.truncated||t.components.collision!==0).map(t=>JSON.stringify({step:t.endStep,reason:t.reason,collision:t.components.collision})).join('\n')),'summary.csv':strToU8(header.join(',')+'\n'+row.join(',')+'\n')});download(`dronelab-${run.id.slice(0,8)}.zip`,zip as BlobPart,'application/zip');}
export function validateRun(run:RunRecord){if(run.manifest.schema!=='run-v1')throw new Error('Unsupported run schema');let step=-1;for(const t of run.transitions){if(t.endStep<t.startStep||t.endStep<step||t.ticks!==t.endStep-t.startStep)throw new Error('Invalid transition timing');if(!Number.isFinite(t.reward)||Math.abs(t.reward-t.components.total)>1e-7)throw new Error('Invalid reward');if(t.observation.sourceStep>t.observation.deliveryStep)throw new Error('Invalid sensor timing');step=t.endStep;}return true;}

